services:
  mystoremanagement:
    image: mystoremanagement
    build:
      context: .
      dockerfile: MyStoreManagement.API/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CONNECTION_DATABASE=${CONNECTION_DATABASE}